agger: "2.0"
info:
  title: Imgur API
  description: mgur's API exposes the entire Imgur infrastructure via a standardized
    programmatic interface. Using Imgur's API, you can do just about anything you
    can do on imgur.com, while using your programming language of choice.
  termsOfService: http://imgur.com/tos
  version: v3
host: api.imgur.com
basePath: /3/
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []