agger: "2.0"
info:
  title: Fitbit Subscription API
  description: The Fitbit API allows developers to interact with Fitbit data in their
    own applications, products and services.
  version: "1"
host: api.fitbit.com
basePath: /1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []