agger: "2.0"
info:
  title: Stack Exchange Events API
  description: The API for managing Stack Exchange events.
  termsOfService: http://stackexchange.com/legal/api-terms-of-use
  version: "2.2"
host: api.stackexchange.com
basePath: /2.2
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []