agger: "2.0"
info:
  title: Marvel Comics API
  description: 'The Marvel Comics API allows developers everywhere to access information
    about Marvel''s vast library of comics&mdash;from what''s coming up, to 70 years
    ago. '
  termsOfService: http://developer.marvel.com/terms
  version: v1
host: gateway.marvel.com
basePath: /docs/public
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions:
  ComicList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  EventList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  CreatorList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  CharacterList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  SeriesList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  StoryList:
    properties:
      available:
        description: This is a default description.
        type: string
      returned:
        description: This is a default description.
        type: string
      collectionURI:
        description: This is a default description.
        type: string
      items:
        description: This is a default description.
        type: string
  CharacterSummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
      role:
        description: This is a default description.
        type: string
  EventSummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
  SeriesSummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
  ComicSummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
  Url:
    properties:
      type:
        description: This is a default description.
        type: string
      url:
        description: This is a default description.
        type: string
  CreatorSummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
      role:
        description: This is a default description.
        type: string
  StorySummary:
    properties:
      resourceURI:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
      type:
        description: This is a default description.
        type: string
  Image:
    properties:
      path:
        description: This is a default description.
        type: string
      extension:
        description: This is a default description.
        type: string
  ComicDate:
    properties:
      type:
        description: This is a default description.
        type: string
      date:
        description: This is a default description.
        type: string
  CharacterDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  EventDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  ComicPrice:
    properties:
      type:
        description: This is a default description.
        type: string
      price:
        description: This is a default description.
        type: string
  EventDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  Creator:
    properties:
      id:
        description: This is a default description.
        type: string
      firstName:
        description: This is a default description.
        type: string
      middleName:
        description: This is a default description.
        type: string
      lastName:
        description: This is a default description.
        type: string
      suffix:
        description: This is a default description.
        type: string
      fullName:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      resourceURI:
        description: This is a default description.
        type: string
      urls:
        description: This is a default description.
        type: string
      thumbnail:
        description: This is a default description.
        type: string
  Event:
    properties:
      id:
        description: This is a default description.
        type: string
      title:
        description: This is a default description.
        type: string
      description:
        description: This is a default description.
        type: string
      resourceURI:
        description: This is a default description.
        type: string
      urls:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      start:
        description: This is a default description.
        type: string
      end:
        description: This is a default description.
        type: string
      thumbnail:
        description: This is a default description.
        type: string
      comics:
        description: This is a default description.
        type: string
  ComicDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  TextObject:
    properties:
      type:
        description: This is a default description.
        type: string
      language:
        description: This is a default description.
        type: string
      text:
        description: This is a default description.
        type: string
  CreatorDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  StoryDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  Character:
    properties:
      id:
        description: This is a default description.
        type: string
      name:
        description: This is a default description.
        type: string
      description:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      resourceURI:
        description: This is a default description.
        type: string
      urls:
        description: This is a default description.
        type: string
      thumbnail:
        description: This is a default description.
        type: string
      comics:
        description: This is a default description.
        type: string
      stories:
        description: This is a default description.
        type: string
      events:
        description: This is a default description.
        type: string
  CharacterDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  ComicDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  Series:
    properties:
      id:
        description: This is a default description.
        type: string
      title:
        description: This is a default description.
        type: string
      description:
        description: This is a default description.
        type: string
      resourceURI:
        description: This is a default description.
        type: string
      urls:
        description: This is a default description.
        type: string
      startYear:
        description: This is a default description.
        type: string
      endYear:
        description: This is a default description.
        type: string
      rating:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      thumbnail:
        description: This is a default description.
        type: string
  SeriesDataWrapper:
    properties:
      code:
        description: This is a default description.
        type: string
      status:
        description: This is a default description.
        type: string
      copyright:
        description: This is a default description.
        type: string
      attributionText:
        description: This is a default description.
        type: string
      attributionHTML:
        description: This is a default description.
        type: string
      data:
        description: This is a default description.
        type: string
      etag:
        description: This is a default description.
        type: string
  SeriesDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  StoryDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  Comic:
    properties:
      id:
        description: This is a default description.
        type: string
      digitalId:
        description: This is a default description.
        type: string
      title:
        description: This is a default description.
        type: string
      issueNumber:
        description: This is a default description.
        type: string
      variantDescription:
        description: This is a default description.
        type: string
      description:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      isbn:
        description: This is a default description.
        type: string
      upc:
        description: This is a default description.
        type: string
      diamondCode:
        description: This is a default description.
        type: string
  CreatorDataContainer:
    properties:
      offset:
        description: This is a default description.
        type: string
      limit:
        description: This is a default description.
        type: string
      total:
        description: This is a default description.
        type: string
      count:
        description: This is a default description.
        type: string
      results:
        description: This is a default description.
        type: string
  Story:
    properties:
      id:
        description: This is a default description.
        type: string
      title:
        description: This is a default description.
        type: string
      description:
        description: This is a default description.
        type: string
      resourceURI:
        description: This is a default description.
        type: string
      type:
        description: This is a default description.
        type: string
      modified:
        description: This is a default description.
        type: string
      thumbnail:
        description: This is a default description.
        type: string
      comics:
        description: This is a default description.
        type: string
      series:
        description: This is a default description.
        type: string
      events:
        description: This is a default description.
        type: string