agger: "2.0"
info:
  title: Twitter Account API
  description: The API for Twitter accounts.
  termsOfService: https://dev.twitter.com/overview/terms
  contact:
    name: Twitter
    url: https://twittercommunity.com/
  version: "1.1"
host: api.twitter.com
basePath: /1.1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []