agger: "2.0"
info:
  title: Twitter Help API
  description: The help API for Twitter.
  termsOfService: http://dev.twitter.com/overview/terms
  contact:
    name: Twitter
    url: https://dev.twitter.com/discussion
  version: "1.1"
host: api.twitter.com
basePath: /1.1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions:
  termsofservice:
    properties:
      tos:
        description: This is a default description.
        type: string