agger: "2.0"
info:
  title: Twitter Followers API
  description: This is the followers API.
  termsOfService: http://dev.twitter.com/overview/terms
  contact:
    name: Twitter
    url: https://dev.twitter.com/discussions
  version: "1.1"
host: api.twitter.com
basePath: /1.1
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []