agger: "2.0"
info:
  title: Flickr Interestingness aPI
  description: The API for managing Flickr Interestingness aPI
  termsOfService: https://www.flickr.com/services/api/tos/
  version: 1.0.0
host: www.flickr.com
basePath: /services/rest/
schemes:
- http
produces:
- application/json
consumes:
- application/json
paths: []
definitions: []